# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

warnings_are_errors: true
sudo: false
cache: packages

env:
  -_R_CHECK_FORCE_SUGGESTS_=false

install:
  - R -e "install.packages('pdftools')"

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
